ink+ cmd to create a new note
inkdropapp/inkdrop-alfred-workflow pull request #4
Opened 2024-09-26 00:56 UTC by picklecillo

# Changes
* moved `search.php` to `inkdrop.php` since its no longer just search
* `defaultNotebook` and `defaultTags` env vars for the new note 
* New `ink+` cmd takes `<title>:<body>`

# To Do
* [ ] Update readme
    * [ ] cmd
    * [ ] env vars
    * [ ] getting a notebook id
* [ ] update screenshots
* [ ]

2024-09-26 07:20 UTC, craftzdog commented
renaming the script file is no problem.
would you update the doc?

2024-09-29 21:42 UTC, picklecillo commented
@craftzdog updated Readme!

2024-10-03 00:43 UTC, craftzdog requested changes
I found a small issue regarding the config. Could you fix this?

2024-10-03 00:43 UTC, craftzdog commented on info.plist
> +		<string>book:book-id</string>
I guess it should be empty by default and throw an error when a user tries to create a new note without specifying it. Otherwise, it creates a note within a non-existing notebook.

2024-10-03 21:59 UTC, picklecillo commented on info.plist
> +		<string>book:book-id</string>
what about something like this @craftzdog? 
<img width="853" alt="image" src="https://github.com/user-attachments/assets/06357c71-bd13-4428-8810-34de90a3ce80">

2024-10-03 22:09 UTC, picklecillo commented on info.plist
> +		<string>book:book-id</string>
Or passing the exception reason:
<img width="378" alt="image" src="https://github.com/user-attachments/assets/cabf2134-3680-46d1-9de6-361c9c43704b">

2024-10-07 07:01 UTC, craftzdog commented on info.plist
> +		<string>book:book-id</string>
I think

- Title: "Failed to create a new Inkdrop note"
- Description: "You have to specify a notebook ID in your workflow config"

would be better.

2024-10-07 14:00 UTC, picklecillo commented on info.plist
> +		<string>book:book-id</string>
noted.
what if the exception was related to the tags config? or something else entirely?
would you want to have:
	* a single description for any exception or 
	* one for bookId, another for tagIds and another as default?

2024-10-10 09:24 UTC, craftzdog commented on info.plist
> +		<string>book:book-id</string>
tags are optional, right?

2024-10-11 19:15 UTC, picklecillo commented on info.plist
> +		<string>book:book-id</string>
yep. but invalid tag ids will also get an exception

2024-10-12 00:01 UTC, craftzdog commented on info.plist
> +		<string>book:book-id</string>
Something like

"Invalid tag IDs"
"Please check the tag IDs you specified in your workflow config."

2024-10-18 14:03 UTC, picklecillo commented on info.plist
> +		<string>book:book-id</string>
Updated!

2024-10-22 06:59 UTC, craftzdog requested changes
Thanks! LGTM except for a typo :)

2024-10-22 06:59 UTC, craftzdog commented on src/inkdrop.php
> +  private $defaultErrorMsg = "Failed to create a new Indrop note";
Typo

2024-10-23 13:18 UTC, picklecillo commented on src/inkdrop.php
> +  private $defaultErrorMsg = "Failed to create a new Indrop note";
ooops

2024-10-23 13:19 UTC, picklecillo commented on src/inkdrop.php
> +  private $defaultErrorMsg = "Failed to create a new Indrop note";
on the app name no less 😅 

fixed!

2024-10-28 07:24 UTC, merged

2024-10-28 07:24 UTC, craftzdog commented
Thanks, @picklecillo! Merged 🎉

2024-10-29 04:52 UTC, craftzdog commented
landed in v0.2.0
https://github.com/inkdropapp/inkdrop-alfred-workflow/releases/tag/v0.2.0